
env:
   global:
     - CONAN_REFERENCE: "cegui/0.8.7"
     - CONAN_USERNAME: "utopia"
     - CONAN_LOGIN_USERNAME: "konradnotantoo"
     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
     - CONAN_CHANNEL: "testing"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/konradnotantoo/utopia"
     - CONAN_REMOTES: "https://api.bintray.com/conan/bincrafters/public-conan"
     - CONAN_BUILD_POLICY: "missing"

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86

      - <<: *linux
        env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=conanio/gcc5 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=conanio/gcc6 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc8 CONAN_ARCHS=x86_64
      - <<: *linux
        env: CONAN_GCC_VERSIONS=9 CONAN_DOCKER_IMAGE=conanio/gcc9 CONAN_ARCHS=x86_64

      # - <<: *osx
      #   osx_image: xcode7.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=7.3
      # - <<: *osx
      #   osx_image: xcode8
      #   env: CONAN_APPLE_CLANG_VERSIONS=8.0
      # - <<: *osx
      #   osx_image: xcode8.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=8.1
      # - <<: *osx
      #   osx_image: xcode9
      #   env: CONAN_APPLE_CLANG_VERSIONS=9.0
      # - <<: *osx
      #   osx_image: xcode9.4
      #   env: CONAN_APPLE_CLANG_VERSIONS=9.1
      # - <<: *osx
      #   osx_image: xcode10.1
      #   env: CONAN_APPLE_CLANG_VERSIONS=10.0

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
